---
name: Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org

      - name: Use npm cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.npm
          key: npm

      - name: Install linters
        run: |
          make install-pre-commit
          make install-linters-binaries
  build:
    name: build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to GitHub registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  upload_files:
    name: Upload files
    runs-on: ubuntu-latest
    needs: build
    env:
      SPACE_NAME: cdn.samarchyan.me
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - uses: BetaHuhn/do-spaces-action@v2.0.109
        with:
          access_key: ${{ secrets.SPACES_ACCESS_KEY}}
          secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          space_name: ${{ env.SPACE_NAME }}
          space_region: nyc3
          source: cdn

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Flush CDN cache
        run: make flush-cdn-cache
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: upload_files
    env:
      PROJECT: homepage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because doesn't work in place.

      - name: Deploy
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/ingress.yaml
          kubectl apply -f deployment/service.yaml
          kubectl rollout restart "deployment/$PROJECT"
          kubectl rollout status "deployment/$PROJECT"
